# codecov configuration document
# https://docs.codecov.io/docs/codecovyml-reference
codecov:
  require_ci_to_pass: yes
  coverage:
    status:
      project:
        default:
          target: auto
          threshold: 0.03%
  comment:
    layout: 'reach, diff, flags, files'
    behavior: default
    require_changes: true
    branches:
      - 'master'
      - 'dev'
