version: 2.1
workflows:
  build_test_release:
    jobs:
      - test
      - build
      - release:
          requires:
            - build
            - test
          filters:
            branches:
              only: /^master|dev|alpha|[0-9]+\.[0-9]+\.x$/

jobs:
  test:
    docker:
      - image: circleci/node:12.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: yarn run lint
      - run: yarn test -w 1 --coverage
      - run: bash <(curl -s https://codecov.io/bash)

  build:
    docker:
      - image: circleci/node:12.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - esm

  release:
    docker:
      - image: circleci/node:12.0

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npx semantic-release